# Correccion del archivo csv de DIM_CALENDAR

In [3]:
#Abrir el archivo que se busca corregir
import pandas as pd
df = pd.read_csv('DIM_CALENDAR.csv', encoding = 'ISO-8859-1' )
df

       WEEK  YEAR  MONTH  WEEK_NUMBER        DATE
0    ene-21  2021      1            1  10/01/2021
1    feb-21  2021      1            2  17/01/2021
2    mar-21  2021      1            3  24/01/2021
3    abr-21  2021      1            4  31/01/2021
4    may-21  2021      2            5  07/02/2021
..      ...   ...    ...          ...         ...
151   48-23  2023     12           48  04/12/2023
152   49-23  2023     12           49  11/12/2023
153   50-23  2023     12           50  18/12/2023
154   51-23  2023     12           51  25/12/2023
155   52-23  2023      1           52  01/01/2024

[156 rows x 5 columns]

In [17]:
#Correccion de la columna WEEK
def corregir_week(valor):
    try:
        meses = {
            'ene': 1, 'feb': 2, 'mar': 3, 'abr': 4,
            'may': 5, 'jun': 6, 'jul': 7, 'ago': 8,
            'sep': 9, 'oct': 10, 'nov': 11, 'dic': 12}

        if isinstance(valor, str) and '-' in valor:
            parte, year = valor.split('-')
            if parte.lower() in meses:
                mes = meses[parte.lower()]
            else:
                mes = int(parte)

            if 1 <= mes <= 12:
                return f'{mes:02d}-{year}'

        return valor

    except:
        return valor

In [19]:
df['WEEK'] = df.apply(
    lambda x: f"{int(x['WEEK_NUMBER']):02d}-{str(x['YEAR'])[-2:]}"
    if pd.notnull(x['WEEK_NUMBER']) and pd.notnull(x['YEAR'])
    else x['WEEK'],
    axis=1)

In [20]:
#Apliacion de la funcion sobre la columna a corregir
df['WEEK'] = df['WEEK'].apply(corregir_week)
df

      WEEK  YEAR  MONTH  WEEK_NUMBER        DATE
0    01-21  2021      1            1  10/01/2021
1    02-21  2021      1            2  17/01/2021
2    03-21  2021      1            3  24/01/2021
3    04-21  2021      1            4  31/01/2021
4    05-21  2021      2            5  07/02/2021
..     ...   ...    ...          ...         ...
151  48-23  2023     12           48  04/12/2023
152  49-23  2023     12           49  11/12/2023
153  50-23  2023     12           50  18/12/2023
154  51-23  2023     12           51  25/12/2023
155  52-23  2023      1           52  01/01/2024

[156 rows x 5 columns]

In [21]:
#Guardar el nuevo archivo corregido
df.to_csv('DIM_WEEK(1).csv', index = False)