# EDA EXPLORATORIO DE DATOS SOBRE LA EMRPESA DE RECKITT

### Cargar y Lectura del archivo

In [1]:
# Importar librerias adecuadas para la lectura del archivo
import pandas as pd 
import numpy as np 

# Lectura del archivo
calendar = pd.read_csv('databses/RECKITT/DIM_CALENDAR.csv',encoding = 'ISO-8859-1')
category = pd.read_csv('databses/RECKITT/DIM_CATEGORY.csv',encoding = 'ISO-8859-1')
product = pd.read_csv('databses/RECKITT/DIM_PRODUCT.csv',encoding = 'ISO-8859-1')
seg = pd.read_csv('databses/RECKITT/DIM_SEGMENT.csv',encoding = 'ISO-8859-1')
week = pd.read_csv('databses/RECKITT/DIM_WEEK(1).csv',encoding = 'ISO-8859-1')
sales = pd.read_csv('databses/RECKITT/1_FACT_SALES.csv',encoding = 'ISO-8859-1')

### Revision y entendimiento de datos cargados

In [2]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    object
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    object
dtypes: int64(3), object(2)
memory usage: 6.2+ KB

In [3]:
category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_CATEGORY  5 non-null      int64
 1   CATEGORY     5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [4]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              505 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             505 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             505 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB

In [5]:
seg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CATEGORY  53 non-null     int64
 1   ATTR1     53 non-null     object
 2   ATTR2     53 non-null     object
 3   ATTR3     53 non-null     object
 4   FORMAT    53 non-null     object
 5   SEGMENT   53 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.6+ KB

In [6]:
week.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    object
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    object
dtypes: int64(3), object(2)
memory usage: 6.2+ KB

In [7]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 19 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ï»¿DATE                      122002 non-null  object
 1   MONTH                        122002 non-null  int64
 2   YEAR                         122002 non-null  int64
 3   WEEK                         122002 non-null  object
 4   MANUFACTER                   122002 non-null  object
 5   BRAND                        122002 non-null  object
 6   ITEM_CODE                    122002 non-null  object
 7   ITEM DESCRIPTION             122002 non-null  object
 8   ID_CATEGORY                  122002 non-null  int64
 9   CATEGORY                     122002 non-null  object
 10  FORMAT                       122002 non-null  object
 11  ATTR1                        122002 non-null  object
 12  ATTR2                        122002 non-null  object
 13  ATTR3                        122002 non-null  object
 14  SEGMENT                      122002 non-null  object
 15  TOTAL_UNIT_SALES             122002 non-null  float64
 16  TOTAL_VALUE_SALES            122002 non-null  float64
 17  TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
 18  REGION                       122002 non-null  object
dtypes: float64(3), int64(3), object(13)
memory usage: 17.7+ MB

### Limpieza de datos

In [8]:
#Correccion de WEEK
def correccion_week(valor):
    try:
        meses = {
            'ene': 1, 'feb': 2, 'mar': 3, 'abr': 4,
            'may': 5, 'jun': 6, 'jul': 7, 'ago': 8,
            'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12
        }
        if isinstance(valor, str) and '-' in valor:
            parte, year = valor.split('-')
            if parte.lower() in meses:
                mes = meses[parte.lower()]
            else:
                mes = int(parte)
            if 1 <= mes <= 12:
                return f'{mes:02d}-{year}'
        return valor
    except:
        return valor

In [9]:
#Correccion de week
week['WEEK'] = week.apply(
    lambda x: f'{int(x['WEEK_NUMBER']):02d}-{str(x['YEAR'])[-2]}'
    if pd.notnull(x['WEEK_NUMBER']) and pd.notnull(x['YEAR'])
    else x['WEEK'], axis = 1)

In [10]:
#Aplicacion de la funcion sobre la columna con errores
week['WEEK'] = week['WEEK'].apply(correccion_week)
week

     WEEK  YEAR  MONTH  WEEK_NUMBER        DATE
0    01-2  2021      1            1  10/01/2021
1    02-2  2021      1            2  17/01/2021
2    03-2  2021      1            3  24/01/2021
3    04-2  2021      1            4  31/01/2021
4    05-2  2021      2            5  07/02/2021
..    ...   ...    ...          ...         ...
151  48-2  2023     12           48  04/12/2023
152  49-2  2023     12           49  11/12/2023
153  50-2  2023     12           50  18/12/2023
154  51-2  2023     12           51  25/12/2023
155  52-2  2023      1           52  01/01/2024

[156 rows x 5 columns]

### Union de Dataframes relevantes

In [11]:
segcat = pd.concat([category,seg],axis = 1)
segcat.fillna(0)

,ID_CATEGORY,CATEGORY,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1.0,FABRIC TREATMENT and SANITIZANTE,1,CLORO,CLORO,BAMBINO,LIQUIDO,CLORO
1,2.0,AIR CARE,1,CLORO,CLORO,GERMICIDA,LIQUIDO,CLORO
2,3.0,LAVAVAJILLAS,1,CLORO,CLORO,MASCOTAS,LIQUIDO,CLORO
3,4.0,MEGA SUPERFICIES,1,CLORO,CLORO,MULTIUSOS,GEL,CLORO
4,5.0,LAVATORY CARE & BRC,1,CLORO,CLORO,MULTIUSOS,LIQUIDO,CLORO
5,0.0,0,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,CLORO
6,0.0,0,1,CLORO,CLORO,NO DEFINIDO,POLVO,CLORO
7,0.0,0,1,CLORO,CLORO,OTR. TIPOS,LIQUIDO,CLORO
8,0.0,0,1,CLORO,CLORO,OTR. TIPOS,POLVO,CLORO
9,0.0,0,1,CLORO,CLORO,ROPA BEBE,LIQUIDO,CLORO
10,0.0,0,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,CLORO
11,0.0,0,1,CLORO,MASCOTAS,MASCOTAS,LIQUIDO,CLORO
12,0.0,0,1,CLORO,MULTIUSOS,MULTIUSOS,GEL,CLORO
13,0.0,0,1,CLORO,NO DEFINIDO,NO DEFINIDO,LIQUIDO,CLORO
14,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,BLANCO,GEL,LIQUIDO & GEL
15,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,BLANCO,POLVO,POLVO
16,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,BLANCO,TOALLAS,OTROS
17,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,PRE TRATAMIENTO
18,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRE TRATAMIENTO
19,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,PRE LAVADOR,POLVO,POLVO
20,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,PRE TRATAMIENTO
21,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,PRE TRATAMIENTO
22,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,ROSA,GEL,LIQUIDO & GEL
23,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,ROSA,LIQUIDO,PRE TRATAMIENTO
24,0.0,0,1,PRE LAVADOR,FABRIC TREATMENT,ROSA,POLVO,POLVO
25,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,BARRA,BARRA
26,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,GEL,LIQUIDO & GEL
27,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUIDO & GEL
28,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,POLVO,POLVO
29,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,COLOR PODER VINAGRE,GEL,LIQUIDO & GEL
30,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,COLOR PODER VINAGRE,LIQUIDO,LIQUIDO & GEL
31,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,BARRA,BARRA
32,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,GEL,LIQUIDO & GEL
33,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,LIQUIDO & GEL
34,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,POLVO,POLVO
35,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,PODER OXIGENO,GEL,LIQUIDO & GEL
36,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,BARRA,BARRA
37,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,GEL,LIQUIDO & GEL
38,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRE TRATAMIENTO
39,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,POLVO,POLVO
40,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,QUITAMANCHAS,GEL,LIQUIDO & GEL
41,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,LIQUIDO & GEL
42,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,QUITAMANCHAS,POLVO,POLVO
43,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUIDO & GEL
44,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,POLVO,POLVO
45,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,LIQUIDO & GEL
46,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,ROPA COLOR,POLVO,POLVO
47,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,ROSA,BARRA,BARRA
48,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,ROSA,GEL,LIQUIDO & GEL
49,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,ROSA,LIQUIDO,LIQUIDO & GEL
50,0.0,0,1,SAFE CLORO,FABRIC TREATMENT,ROSA,POLVO,POLVO
51,0.0,0,1,SAFE CLORO,PRE LAVADOR,PRE LAVADOR,GEL,PRE TRATAMIENTO
52,0.0,0,1,SANITIZANTE,SANITIZANTE,SANITIZANTE,LIQUIDO,SANITIZANTE

In [12]:
#ELiminar varias columnas
segcat1 = segcat.drop(columns = ['ID_CATEGORY','CATEGORY','CATEGORY','ATTR2','ATTR3'])
segcat1.drop_duplicates()

          ATTR1   FORMAT          SEGMENT
0         CLORO  LIQUIDO            CLORO
3         CLORO      GEL            CLORO
6         CLORO    POLVO            CLORO
14  PRE LAVADOR      GEL    LIQUIDO & GEL
15  PRE LAVADOR    POLVO            POLVO
16  PRE LAVADOR  TOALLAS            OTROS
17  PRE LAVADOR  LIQUIDO  PRE TRATAMIENTO
25   SAFE CLORO    BARRA            BARRA
26   SAFE CLORO      GEL    LIQUIDO & GEL
27   SAFE CLORO  LIQUIDO    LIQUIDO & GEL
28   SAFE CLORO    POLVO            POLVO
38   SAFE CLORO  LIQUIDO  PRE TRATAMIENTO
51   SAFE CLORO      GEL  PRE TRATAMIENTO
52  SANITIZANTE  LIQUIDO      SANITIZANTE

In [13]:
prodsale = pd.concat([product,sales],axis = 1)
prodsale.fillna(0)

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,ï»¿DATE,...,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,SEGMENT,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,INDS. ALEN,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,28/08/2022,...,AIR CARE,POLVO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BLEACH,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,INDS. ALEN,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,28/08/2022,...,AIR CARE,POLVO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BLEACH,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,INDS. ALEN,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,28/08/2022,...,AIR CARE,POLVO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BLEACH,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,INDS. ALEN,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,28/08/2022,...,AIR CARE,POLVO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BLEACH,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,INDS. ALEN,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,28/08/2022,...,AIR CARE,POLVO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BLEACH,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121997,0,0,0,0,0.0,0,0,0,0,03/07/2023,...,AIR CARE,POLVO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BLEACH,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,0,0,0,0,0.0,0,0,0,0,03/07/2023,...,FABRIC TREATMENT and SANIT\r\n,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,0,0,0,0,0.0,0,0,0,0,03/07/2023,...,AIR CARE,POLVO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BLEACH,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,0,0,0,0,0.0,0,0,0,0,03/07/2023,...,AIR CARE,POLVO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BLEACH,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,0,0,0,0,0.0,0,0,0,0,03/07/2023,...,AIR CARE,POLVO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BLEACH,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

In [14]:
prodsale.drop(columns = ['MANUFACTURER','ITEM_CODE','ITEM DESCRIPTION','CATEGORY','FORMAT','ATTR2','ATTR3','MONTH'],inplace= True)
prodsale.drop_duplicates().fillna(0)

,BRAND,ITEM,ITEM_DESCRIPTION,ATTR1,ï»¿DATE,YEAR,WEEK,MANUFACTER,BRAND,ID_CATEGORY,ATTR1,SEGMENT,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,CLORO,28/08/2022,2022,34-22,RECKITT,VANISH,2,SAFE BLEACH,BLEACH,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,CLORO,28/08/2022,2022,34-22,RECKITT,VANISH,2,SAFE BLEACH,BLEACH,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,CLORO,28/08/2022,2022,34-22,RECKITT,VANISH,2,SAFE BLEACH,BLEACH,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,CLORO,28/08/2022,2022,34-22,RECKITT,VANISH,2,SAFE BLEACH,BLEACH,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,CLORO,28/08/2022,2022,34-22,RECKITT,VANISH,2,SAFE BLEACH,BLEACH,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121997,0,0,0,0,03/07/2023,2023,26-23,RECKITT,VANISH,2,SAFE BLEACH,BLEACH,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,0,0,0,0,03/07/2023,2023,26-23,RECKITT,VANISH,1,CLORO,BLEACH,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,0,0,0,0,03/07/2023,2023,26-23,RECKITT,VANISH,2,SAFE BLEACH,BLEACH,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,0,0,0,0,03/07/2023,2023,26-23,RECKITT,VANISH,2,SAFE BLEACH,BLEACH,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,0,0,0,0,03/07/2023,2023,26-23,RECKITT,VANISH,2,SAFE BLEACH,BLEACH,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

In [15]:
cols_a_eliminar = prodsale.columns[[1, 2]].tolist() + ['ID_CATEGORY']
# Todas las columnas MENOS la de la posición 3 (el primer ATTR1)
posiciones_a_mantener = [i for i in range(len(prodsale.columns)) if i not in (0, 3)]
prodsale = prodsale.iloc[:, posiciones_a_mantener]
prodsale = prodsale.drop(columns=cols_a_eliminar)
prodsale

,ï»¿DATE,YEAR,WEEK,MANUFACTER,BRAND,ATTR1,SEGMENT,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,28/08/2022,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,28/08/2022,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,28/08/2022,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,28/08/2022,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,28/08/2022,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...,...,...,...,...,...
121997,03/07/2023,2023,26-23,RECKITT,VANISH,SAFE BLEACH,BLEACH,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,03/07/2023,2023,26-23,RECKITT,VANISH,CLORO,BLEACH,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,03/07/2023,2023,26-23,RECKITT,VANISH,SAFE BLEACH,BLEACH,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,03/07/2023,2023,26-23,RECKITT,VANISH,SAFE BLEACH,BLEACH,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,03/07/2023,2023,26-23,RECKITT,VANISH,SAFE BLEACH,BLEACH,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

In [16]:
prodsale.sample(5)

,ï»¿DATE,YEAR,WEEK,MANUFACTER,BRAND,ATTR1,SEGMENT,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
90655,24/04/2023,2023,16-23,CHURCH & DWIGHT,OXI CLEAN,SAFE BLEACH,BLEACH,0.245,62.003,2.602,TOTAL AUTOS AREA 4
45780,11/09/2022,2022,36-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,0.085,3.762,3.269,TOTAL AUTOS AREA 4
27906,16/01/2022,2022,02-22,CLOROX,CLOROX,CLORO,BLEACH,0.185,9.617,2.608,TOTAL AUTOS AREA 2
13018,16/10/2022,2022,41-22,BLANQUEADORA MEXICANA,LOS PATITOS,CLORO,BLEACH,1.566,76.965,10.726,TOTAL AUTOS SCANNING MEXICO
94591,18/12/2022,2022,50-22,INDS. ALEN,CLORALEX,CLORO,BLEACH,1.288,62.536,11.103,TOTAL AUTOS AREA 6

### Aplicar transformaciones necesarias

In [17]:
prodsale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 11 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ï»¿DATE                      122002 non-null  object
 1   YEAR                         122002 non-null  int64
 2   WEEK                         122002 non-null  object
 3   MANUFACTER                   122002 non-null  object
 4   BRAND                        122002 non-null  object
 5   ATTR1                        122002 non-null  object
 6   SEGMENT                      122002 non-null  object
 7   TOTAL_UNIT_SALES             122002 non-null  float64
 8   TOTAL_VALUE_SALES            122002 non-null  float64
 9   TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
 10  REGION                       122002 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 10.2+ MB

In [25]:
#Transformaciones principales
prodsale = prodsale.astype({
    'YEAR': int,
    'WEEK': 'string',
    'MANUFACTER': 'string',
    'BRAND': 'string',
    'ATTR1': 'string',
    'SEGMENT': 'string',
    'TOTAL_UNIT_SALES': float,
    'TOTAL_VALUE_SALES': float,
    'TOTAL_UNIT_AVG_WEEKLY_SALES': float,
    'REGION': 'string' 
})

prodsale = prodsale.rename(columns={'ï»¿DATE':'DATE'})

In [28]:
prodsale['DATE'] = pd.to_datetime(prodsale['DATE'])
prodsale

,DATE,YEAR,WEEK,MANUFACTER,BRAND,ATTR1,SEGMENT,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,2022-08-28,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,2022-08-28,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,2022-08-28,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,2022-08-28,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,2022-08-28,2022,34-22,RECKITT,VANISH,SAFE BLEACH,BLEACH,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...,...,...,...,...,...
121997,2023-07-03,2023,26-23,RECKITT,VANISH,SAFE BLEACH,BLEACH,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,2023-07-03,2023,26-23,RECKITT,VANISH,CLORO,BLEACH,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,2023-07-03,2023,26-23,RECKITT,VANISH,SAFE BLEACH,BLEACH,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,2023-07-03,2023,26-23,RECKITT,VANISH,SAFE BLEACH,BLEACH,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,2023-07-03,2023,26-23,RECKITT,VANISH,SAFE BLEACH,BLEACH,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

### Guardar conjunto de datos consolidados

In [29]:
prodsale.to_csv('final_prodsale.csv')