# 1. Cargar y explorar el archivo de datos

In [1]:
#Cargar el archivo de "DIM_CALENDAR"
import pandas as pd
calendar = pd.read_csv('DIM_WEEK(1).csv', encoding = 'ISO-8859-1')
calendar

      WEEK  YEAR  MONTH  WEEK_NUMBER        DATE
0    01-21  2021      1            1  10/01/2021
1    02-21  2021      1            2  17/01/2021
2    03-21  2021      1            3  24/01/2021
3    04-21  2021      1            4  31/01/2021
4    05-21  2021      2            5  07/02/2021
..     ...   ...    ...          ...         ...
151  48-23  2023     12           48  04/12/2023
152  49-23  2023     12           49  11/12/2023
153  50-23  2023     12           50  18/12/2023
154  51-23  2023     12           51  25/12/2023
155  52-23  2023      1           52  01/01/2024

[156 rows x 5 columns]

In [2]:
##Cargar el archivo de "DIM_CATEGORY"
category = pd.read_csv('DIM_CATEGORY.csv', encoding = 'ISO-8859-1')
category

   ID_CATEGORY                          CATEGORY
0            1  FABRIC TREATMENT and SANITIZANTE
1            2                         AIR CARE
2            3                      LAVAVAJILLAS
3            4                  MEGA SUPERFICIES
4            5               LAVATORY CARE & BRC

In [3]:
#Cargar el archivo de "DIM_PRODUCT"
product = pd.read_csv('DIM_PRODUCT.csv', encoding = 'ISO-8859-1')
product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7.50E+12,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
502,INDS. ALEN,CLORALEX,-,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,-,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [4]:
#Cargar el archivo de "DIM_SEGMENT"
segment = pd.read_csv('DIM_SEGMENT.csv', encoding = 'ISO-8859-1')
segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,CLORO,CLORO,BAMBINO,LIQUIDO,CLORO
1,1,CLORO,CLORO,GERMICIDA,LIQUIDO,CLORO
2,1,CLORO,CLORO,MASCOTAS,LIQUIDO,CLORO
3,1,CLORO,CLORO,MULTIUSOS,GEL,CLORO
4,1,CLORO,CLORO,MULTIUSOS,LIQUIDO,CLORO
5,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,CLORO
6,1,CLORO,CLORO,NO DEFINIDO,POLVO,CLORO
7,1,CLORO,CLORO,OTR. TIPOS,LIQUIDO,CLORO
8,1,CLORO,CLORO,OTR. TIPOS,POLVO,CLORO
9,1,CLORO,CLORO,ROPA BEBE,LIQUIDO,CLORO
10,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,CLORO
11,1,CLORO,MASCOTAS,MASCOTAS,LIQUIDO,CLORO
12,1,CLORO,MULTIUSOS,MULTIUSOS,GEL,CLORO
13,1,CLORO,NO DEFINIDO,NO DEFINIDO,LIQUIDO,CLORO
14,1,PRE LAVADOR,FABRIC TREATMENT,BLANCO,GEL,LIQUIDO & GEL
15,1,PRE LAVADOR,FABRIC TREATMENT,BLANCO,POLVO,POLVO
16,1,PRE LAVADOR,FABRIC TREATMENT,BLANCO,TOALLAS,OTROS
17,1,PRE LAVADOR,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,PRE TRATAMIENTO
18,1,PRE LAVADOR,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRE TRATAMIENTO
19,1,PRE LAVADOR,FABRIC TREATMENT,PRE LAVADOR,POLVO,POLVO
20,1,PRE LAVADOR,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,PRE TRATAMIENTO
21,1,PRE LAVADOR,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,PRE TRATAMIENTO
22,1,PRE LAVADOR,FABRIC TREATMENT,ROSA,GEL,LIQUIDO & GEL
23,1,PRE LAVADOR,FABRIC TREATMENT,ROSA,LIQUIDO,PRE TRATAMIENTO
24,1,PRE LAVADOR,FABRIC TREATMENT,ROSA,POLVO,POLVO
25,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,BARRA,BARRA
26,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,GEL,LIQUIDO & GEL
27,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUIDO & GEL
28,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,POLVO,POLVO
29,1,SAFE CLORO,FABRIC TREATMENT,COLOR PODER VINAGRE,GEL,LIQUIDO & GEL
30,1,SAFE CLORO,FABRIC TREATMENT,COLOR PODER VINAGRE,LIQUIDO,LIQUIDO & GEL
31,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,BARRA,BARRA
32,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,GEL,LIQUIDO & GEL
33,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,LIQUIDO & GEL
34,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,POLVO,POLVO
35,1,SAFE CLORO,FABRIC TREATMENT,PODER OXIGENO,GEL,LIQUIDO & GEL
36,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,BARRA,BARRA
37,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,GEL,LIQUIDO & GEL
38,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRE TRATAMIENTO
39,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,POLVO,POLVO
40,1,SAFE CLORO,FABRIC TREATMENT,QUITAMANCHAS,GEL,LIQUIDO & GEL
41,1,SAFE CLORO,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,LIQUIDO & GEL
42,1,SAFE CLORO,FABRIC TREATMENT,QUITAMANCHAS,POLVO,POLVO
43,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUIDO & GEL
44,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,POLVO,POLVO
45,1,SAFE CLORO,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,LIQUIDO & GEL
46,1,SAFE CLORO,FABRIC TREATMENT,ROPA COLOR,POLVO,POLVO
47,1,SAFE CLORO,FABRIC TREATMENT,ROSA,BARRA,BARRA
48,1,SAFE CLORO,FABRIC TREATMENT,ROSA,GEL,LIQUIDO & GEL
49,1,SAFE CLORO,FABRIC TREATMENT,ROSA,LIQUIDO,LIQUIDO & GEL
50,1,SAFE CLORO,FABRIC TREATMENT,ROSA,POLVO,POLVO
51,1,SAFE CLORO,PRE LAVADOR,PRE LAVADOR,GEL,PRE TRATAMIENTO
52,1,SANITIZANTE,SANITIZANTE,SANITIZANTE,LIQUIDO,SANITIZANTE

In [5]:
#Cargar el archivo de "FACT_SALES"
sales = pd.read_csv('FACT_SALES.csv', encoding = 'ISO-8859-1')
sales

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7.50E+12,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7.70E+12,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7.50E+12,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7.50E+12,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,26-23,7.50E+12,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,26-23,7.50E+12,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,26-23,7.50E+12,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

## DIM_CALENDAR

In [6]:
#Uso de .head() para exploracion del Data Frame
calendar.head()

    WEEK  YEAR  MONTH  WEEK_NUMBER        DATE
0  01-21  2021      1            1  10/01/2021
1  02-21  2021      1            2  17/01/2021
2  03-21  2021      1            3  24/01/2021
3  04-21  2021      1            4  31/01/2021
4  05-21  2021      2            5  07/02/2021

In [7]:
#Uso de .describe() para exploracion del Data Frame
calendar.describe()

              YEAR       MONTH  WEEK_NUMBER
count   156.000000  156.000000   156.000000
mean   2022.000000    6.487179    26.500000
std       0.819126    3.459419    15.056667
min    2021.000000    1.000000     1.000000
25%    2021.000000    3.750000    13.750000
50%    2022.000000    6.500000    26.500000
75%    2023.000000    9.250000    39.250000
max    2023.000000   12.000000    52.000000

In [8]:
#Uso de .info() para exploracion del Data Frame
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    object
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    object
dtypes: int64(3), object(2)
memory usage: 6.2+ KB

## DIM_CATEGORY

In [9]:
#Uso de .head() para exploracion del Data Frame
category.head()

   ID_CATEGORY                          CATEGORY
0            1  FABRIC TREATMENT and SANITIZANTE
1            2                         AIR CARE
2            3                      LAVAVAJILLAS
3            4                  MEGA SUPERFICIES
4            5               LAVATORY CARE & BRC

In [10]:
#Uso de .describe() para exploracion del Data Frame
category.describe()

       ID_CATEGORY
count     5.000000
mean      3.000000
std       1.581139
min       1.000000
25%       2.000000
50%       3.000000
75%       4.000000
max       5.000000

In [11]:
#Uso de .info() para exploracion del Data Frame
category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_CATEGORY  5 non-null      int64
 1   CATEGORY     5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

## DIM_SEGMENT

In [12]:
#Uso de .head() para exploracion del Data Frame
segment.head()

   CATEGORY  ATTR1  ATTR2      ATTR3   FORMAT SEGMENT
0         1  CLORO  CLORO    BAMBINO  LIQUIDO   CLORO
1         1  CLORO  CLORO  GERMICIDA  LIQUIDO   CLORO
2         1  CLORO  CLORO   MASCOTAS  LIQUIDO   CLORO
3         1  CLORO  CLORO  MULTIUSOS      GEL   CLORO
4         1  CLORO  CLORO  MULTIUSOS  LIQUIDO   CLORO

In [13]:
#Uso de .describe() para exploracion del Data Frame
segment.describe()

       CATEGORY
count      53.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0

In [14]:
#Uso de .info() para exploracion del Data Frame
segment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CATEGORY  53 non-null     int64
 1   ATTR1     53 non-null     object
 2   ATTR2     53 non-null     object
 3   ATTR3     53 non-null     object
 4   FORMAT    53 non-null     object
 5   SEGMENT   53 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.6+ KB

## DIM_PRODUCT

In [15]:
#Uso de .head() para exploracion del Data Frame
product.head()

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [16]:
#Uso de .describe() para exploracion del Data Frame
product.describe()

       CATEGORY
count     505.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0

In [17]:
#Uso de .info() para exploracion del Data Frame
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              505 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             505 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             505 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB

## FACT_SALES

In [18]:
#Uso de .head() para exploracion del Data Frame
sales.head()

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7.50E+12,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7.70E+12,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7.50E+12,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7.50E+12,2.037,182.839,5.375,TOTAL AUTOS AREA 5

In [19]:
#Uso de .describe() para exploracion del Data Frame
sales.describe()

       TOTAL_UNIT_SALES  TOTAL_VALUE_SALES  TOTAL_UNIT_AVG_WEEKLY_SALES
count     122002.000000      122002.000000                122002.000000
mean           3.211097          90.513761                    10.099904
std           14.496009         350.236505                    22.650142
min            0.000000           0.001000                     0.042000
25%            0.063000           2.662000                     2.316000
50%            0.367000          16.812000                     3.993500
75%            1.520000          62.961500                     8.898000
max          504.681000       12236.759000                   794.000000

In [20]:
#Uso de .info() para exploracion del Data Frame
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 6 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   WEEK                         122002 non-null  object
 1   ITEM_CODE                    122002 non-null  object
 2   TOTAL_UNIT_SALES             122002 non-null  float64
 3   TOTAL_VALUE_SALES            122002 non-null  float64
 4   TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
 5   REGION                       122002 non-null  object
dtypes: float64(3), object(3)
memory usage: 5.6+ MB

# 2. Limpieza de Datos

## DIM_CALENDAR

In [21]:
#Verificacion de valores nulos
calendar.isna()

      WEEK   YEAR  MONTH  WEEK_NUMBER   DATE
0    False  False  False        False  False
1    False  False  False        False  False
2    False  False  False        False  False
3    False  False  False        False  False
4    False  False  False        False  False
..     ...    ...    ...          ...    ...
151  False  False  False        False  False
152  False  False  False        False  False
153  False  False  False        False  False
154  False  False  False        False  False
155  False  False  False        False  False

[156 rows x 5 columns]

In [22]:
#Verificacion y eliminacion de datos duplicados
calendar = calendar.drop_duplicates()

calendar

      WEEK  YEAR  MONTH  WEEK_NUMBER        DATE
0    01-21  2021      1            1  10/01/2021
1    02-21  2021      1            2  17/01/2021
2    03-21  2021      1            3  24/01/2021
3    04-21  2021      1            4  31/01/2021
4    05-21  2021      2            5  07/02/2021
..     ...   ...    ...          ...         ...
151  48-23  2023     12           48  04/12/2023
152  49-23  2023     12           49  11/12/2023
153  50-23  2023     12           50  18/12/2023
154  51-23  2023     12           51  25/12/2023
155  52-23  2023      1           52  01/01/2024

[156 rows x 5 columns]

In [23]:
calendar.isnull().sum()

WEEK           0
YEAR           0
MONTH          0
WEEK_NUMBER    0
DATE           0
dtype: int64

In [24]:
#Aseguracion del tipo de dato en cada elemento
calendar['YEAR'].astype(int)
calendar['MONTH'].astype(int)
calendar['WEEK_NUMBER'].astype(int)

0       1
1       2
2       3
3       4
4       5
       ..
151    48
152    49
153    50
154    51
155    52
Name: WEEK_NUMBER, Length: 156, dtype: int64

## DIM CATEGORY

In [25]:
#Verificacion de valores nulos
category.isna()

   ID_CATEGORY  CATEGORY
0        False     False
1        False     False
2        False     False
3        False     False
4        False     False

In [26]:
#Verificacion y eliminacion de datos duplicados
category = category.drop_duplicates()

category

   ID_CATEGORY                          CATEGORY
0            1  FABRIC TREATMENT and SANITIZANTE
1            2                         AIR CARE
2            3                      LAVAVAJILLAS
3            4                  MEGA SUPERFICIES
4            5               LAVATORY CARE & BRC

In [27]:
category.isnull().sum()

ID_CATEGORY    0
CATEGORY       0
dtype: int64

In [28]:
#Aseguracion del tipo de dato en cada elemento
category['ID_CATEGORY'].astype(int)

0    1
1    2
2    3
3    4
4    5
Name: ID_CATEGORY, dtype: int64

## DIM SEGMENT

In [29]:
#Verificacion de valores nulos
segment.isna()

    CATEGORY  ATTR1  ATTR2  ATTR3  FORMAT  SEGMENT
0      False  False  False  False   False    False
1      False  False  False  False   False    False
2      False  False  False  False   False    False
3      False  False  False  False   False    False
4      False  False  False  False   False    False
5      False  False  False  False   False    False
6      False  False  False  False   False    False
7      False  False  False  False   False    False
8      False  False  False  False   False    False
9      False  False  False  False   False    False
10     False  False  False  False   False    False
11     False  False  False  False   False    False
12     False  False  False  False   False    False
13     False  False  False  False   False    False
14     False  False  False  False   False    False
15     False  False  False  False   False    False
16     False  False  False  False   False    False
17     False  False  False  False   False    False
18     False  False  False  False   False    False
19     False  False  False  False   False    False
20     False  False  False  False   False    False
21     False  False  False  False   False    False
22     False  False  False  False   False    False
23     False  False  False  False   False    False
24     False  False  False  False   False    False
25     False  False  False  False   False    False
26     False  False  False  False   False    False
27     False  False  False  False   False    False
28     False  False  False  False   False    False
29     False  False  False  False   False    False
30     False  False  False  False   False    False
31     False  False  False  False   False    False
32     False  False  False  False   False    False
33     False  False  False  False   False    False
34     False  False  False  False   False    False
35     False  False  False  False   False    False
36     False  False  False  False   False    False
37     False  False  False  False   False    False
38     False  False  False  False   False    False
39     False  False  False  False   False    False
40     False  False  False  False   False    False
41     False  False  False  False   False    False
42     False  False  False  False   False    False
43     False  False  False  False   False    False
44     False  False  False  False   False    False
45     False  False  False  False   False    False
46     False  False  False  False   False    False
47     False  False  False  False   False    False
48     False  False  False  False   False    False
49     False  False  False  False   False    False
50     False  False  False  False   False    False
51     False  False  False  False   False    False
52     False  False  False  False   False    False

In [30]:
#Verificacion y eliminacion de datos duplicados
segment = segment.drop_duplicates()

segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,CLORO,CLORO,BAMBINO,LIQUIDO,CLORO
1,1,CLORO,CLORO,GERMICIDA,LIQUIDO,CLORO
2,1,CLORO,CLORO,MASCOTAS,LIQUIDO,CLORO
3,1,CLORO,CLORO,MULTIUSOS,GEL,CLORO
4,1,CLORO,CLORO,MULTIUSOS,LIQUIDO,CLORO
5,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,CLORO
6,1,CLORO,CLORO,NO DEFINIDO,POLVO,CLORO
7,1,CLORO,CLORO,OTR. TIPOS,LIQUIDO,CLORO
8,1,CLORO,CLORO,OTR. TIPOS,POLVO,CLORO
9,1,CLORO,CLORO,ROPA BEBE,LIQUIDO,CLORO
11,1,CLORO,MASCOTAS,MASCOTAS,LIQUIDO,CLORO
12,1,CLORO,MULTIUSOS,MULTIUSOS,GEL,CLORO
13,1,CLORO,NO DEFINIDO,NO DEFINIDO,LIQUIDO,CLORO
14,1,PRE LAVADOR,FABRIC TREATMENT,BLANCO,GEL,LIQUIDO & GEL
15,1,PRE LAVADOR,FABRIC TREATMENT,BLANCO,POLVO,POLVO
16,1,PRE LAVADOR,FABRIC TREATMENT,BLANCO,TOALLAS,OTROS
17,1,PRE LAVADOR,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,PRE TRATAMIENTO
18,1,PRE LAVADOR,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRE TRATAMIENTO
19,1,PRE LAVADOR,FABRIC TREATMENT,PRE LAVADOR,POLVO,POLVO
20,1,PRE LAVADOR,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,PRE TRATAMIENTO
21,1,PRE LAVADOR,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,PRE TRATAMIENTO
22,1,PRE LAVADOR,FABRIC TREATMENT,ROSA,GEL,LIQUIDO & GEL
23,1,PRE LAVADOR,FABRIC TREATMENT,ROSA,LIQUIDO,PRE TRATAMIENTO
24,1,PRE LAVADOR,FABRIC TREATMENT,ROSA,POLVO,POLVO
25,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,BARRA,BARRA
26,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,GEL,LIQUIDO & GEL
27,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUIDO & GEL
28,1,SAFE CLORO,FABRIC TREATMENT,BLANCO,POLVO,POLVO
29,1,SAFE CLORO,FABRIC TREATMENT,COLOR PODER VINAGRE,GEL,LIQUIDO & GEL
30,1,SAFE CLORO,FABRIC TREATMENT,COLOR PODER VINAGRE,LIQUIDO,LIQUIDO & GEL
31,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,BARRA,BARRA
32,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,GEL,LIQUIDO & GEL
33,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,LIQUIDO & GEL
34,1,SAFE CLORO,FABRIC TREATMENT,OTR. TIPOS,POLVO,POLVO
35,1,SAFE CLORO,FABRIC TREATMENT,PODER OXIGENO,GEL,LIQUIDO & GEL
36,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,BARRA,BARRA
37,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,GEL,LIQUIDO & GEL
38,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRE TRATAMIENTO
39,1,SAFE CLORO,FABRIC TREATMENT,PRE LAVADOR,POLVO,POLVO
40,1,SAFE CLORO,FABRIC TREATMENT,QUITAMANCHAS,GEL,LIQUIDO & GEL
41,1,SAFE CLORO,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,LIQUIDO & GEL
42,1,SAFE CLORO,FABRIC TREATMENT,QUITAMANCHAS,POLVO,POLVO
45,1,SAFE CLORO,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,LIQUIDO & GEL
46,1,SAFE CLORO,FABRIC TREATMENT,ROPA COLOR,POLVO,POLVO
47,1,SAFE CLORO,FABRIC TREATMENT,ROSA,BARRA,BARRA
48,1,SAFE CLORO,FABRIC TREATMENT,ROSA,GEL,LIQUIDO & GEL
49,1,SAFE CLORO,FABRIC TREATMENT,ROSA,LIQUIDO,LIQUIDO & GEL
50,1,SAFE CLORO,FABRIC TREATMENT,ROSA,POLVO,POLVO
51,1,SAFE CLORO,PRE LAVADOR,PRE LAVADOR,GEL,PRE TRATAMIENTO
52,1,SANITIZANTE,SANITIZANTE,SANITIZANTE,LIQUIDO,SANITIZANTE

In [31]:
segment.isnull().sum()

CATEGORY    0
ATTR1       0
ATTR2       0
ATTR3       0
FORMAT      0
SEGMENT     0
dtype: int64

In [32]:
#Aseguracion del tipo de dato en cada elemento
segment['CATEGORY'].astype(int)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
45    1
46    1
47    1
48    1
49    1
50    1
51    1
52    1
Name: CATEGORY, dtype: int64

## DIM PRODUCT

In [33]:
#Verificacion de valores nulos
product.isna()

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
500,False,False,False,False,False,False,False,False,False
501,False,False,False,False,False,False,False,False,False
502,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False

In [34]:
#Verificacion y eliminacion de datos duplicados
product = product.drop_duplicates()

product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7.50E+12,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
502,INDS. ALEN,CLORALEX,-,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,-,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [35]:
product.isnull().sum()

MANUFACTURER        0
BRAND               0
ITEM                0
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               0
ATTR2               0
ATTR3               0
dtype: int64

In [36]:
#Aseguracion del tipo de dato en cada elemento
product['CATEGORY'].astype(int)

0      1
1      1
2      1
3      1
4      1
      ..
500    1
501    1
502    1
503    1
504    1
Name: CATEGORY, Length: 505, dtype: int64

## FACT SALES

In [37]:
#Verificacion de valores nulos
sales.isna()

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
121997,False,False,False,False,False,False
121998,False,False,False,False,False,False
121999,False,False,False,False,False,False
122000,False,False,False,False,False,False
122001,False,False,False,False,False,False

In [38]:
#Verificacion y eliminacion de datos duplicados
sales = sales.drop_duplicates()

sales

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7.50E+12,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7.70E+12,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7.50E+12,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7.50E+12,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,26-23,7.50E+12,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,26-23,7.50E+12,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,26-23,7.50E+12,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

In [39]:
sales.isnull().sum()

WEEK                           0
ITEM_CODE                      0
TOTAL_UNIT_SALES               0
TOTAL_VALUE_SALES              0
TOTAL_UNIT_AVG_WEEKLY_SALES    0
REGION                         0
dtype: int64

In [40]:
#Aseguracion del tipo de dato en cada elemento
sales['TOTAL_UNIT_SALES'].astype(float)
sales['TOTAL_VALUE_SALES'].astype(float)
sales['TOTAL_UNIT_AVG_WEEKLY_SALES'].astype(float)

0          1.000
1          2.916
2          5.171
3          1.833
4          5.375
           ...
121997     4.000
121998     2.797
121999     9.102
122000    22.172
122001     2.068
Name: TOTAL_UNIT_AVG_WEEKLY_SALES, Length: 121904, dtype: float64

# 3. Union de DataFrames Relevantes

In [41]:
#Correccion del archivo DIM_CALENDAR para poder hacer un merge con otro DataFrame

In [42]:
#Union de DataFrame(DIM_CALENDAR & FACT_SALES)
sales_week = pd.concat([sales,calendar], axis = 1)
sales_week

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,WEEK,YEAR,MONTH,WEEK_NUMBER,DATE
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,01-21,2021.0,1.0,1.0,10/01/2021
1,34-22,7.50E+12,0.487,116.519,2.916,TOTAL AUTOS AREA 5,02-21,2021.0,1.0,2.0,17/01/2021
2,34-22,7.70E+12,1.391,68.453,5.171,TOTAL AUTOS AREA 5,03-21,2021.0,1.0,3.0,24/01/2021
3,34-22,7.50E+12,0.022,1.481,1.833,TOTAL AUTOS AREA 5,04-21,2021.0,1.0,4.0,31/01/2021
4,34-22,7.50E+12,2.037,182.839,5.375,TOTAL AUTOS AREA 5,05-21,2021.0,2.0,5.0,07/02/2021
...,...,...,...,...,...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO,NaN,NaN,NaN,NaN,NaN
121998,26-23,7.50E+12,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,NaN,NaN,NaN,NaN,NaN
121999,26-23,7.50E+12,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,NaN,NaN,NaN,NaN,NaN
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO,NaN,NaN,NaN,NaN,NaN
122001,26-23,7.50E+12,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,NaN,NaN,NaN,NaN,NaN

In [43]:
#Union de DataFrames (DIM_PRODUCT & FACT_SALES)
prod_sale = pd.concat ([product,sales], axis = 1)
prod_sale

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,INDS. ALEN,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,INDS. ALEN,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.50E+12,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,INDS. ALEN,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.70E+12,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,INDS. ALEN,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.50E+12,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,INDS. ALEN,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1.0,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.50E+12,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26-23,7.50E+12,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26-23,7.50E+12,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26-23,7.50E+12,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

# 4. Transformaciones necesarias

## Sales_Week
### (DataFrame unido)

In [44]:
#Limpieza del DataFrame eliminando duplicados y transformacion de tipo de datos
sales_week = sales_week.dropna()
sales_week = sales_week.drop_duplicates()
sales_week['MONTH'] = sales_week['MONTH'].astype(int)
sales_week['WEEK_NUMBER'] = sales_week ['WEEK_NUMBER'].astype(int)
sales_week['YEAR'] = sales_week['YEAR'].astype(int)

sales_week

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,WEEK,YEAR,MONTH,WEEK_NUMBER,DATE
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,01-21,2021,1,1,10/01/2021
1,34-22,7.50E+12,0.487,116.519,2.916,TOTAL AUTOS AREA 5,02-21,2021,1,2,17/01/2021
2,34-22,7.70E+12,1.391,68.453,5.171,TOTAL AUTOS AREA 5,03-21,2021,1,3,24/01/2021
3,34-22,7.50E+12,0.022,1.481,1.833,TOTAL AUTOS AREA 5,04-21,2021,1,4,31/01/2021
4,34-22,7.50E+12,2.037,182.839,5.375,TOTAL AUTOS AREA 5,05-21,2021,2,5,07/02/2021
...,...,...,...,...,...,...,...,...,...,...,...
151,44-22,7.50E+12,0.772,32.419,2.756,TOTAL AUTOS AREA 2,48-23,2023,12,48,04/12/2023
152,44-22,7.50E+12,0.513,14.107,3.800,TOTAL AUTOS AREA 2,49-23,2023,12,49,11/12/2023
153,44-22,7.50E+12,12.849,227.073,26.658,TOTAL AUTOS AREA 2,50-23,2023,12,50,18/12/2023
154,44-22,7.50E+12,19.887,345.292,31.973,TOTAL AUTOS AREA 2,51-23,2023,12,51,25/12/2023
155,44-22,7.50E+12,7.119,194.320,15.510,TOTAL AUTOS AREA 2,52-23,2023,1,52,01/01/2024

In [45]:
#Estandarizacion de datos de la columna ITEM_CODE
sales_week['ITEM_CODE'] = sales_week['ITEM_CODE'].astype(str)
sales_week['ITEM_CODE'] = sales_week['ITEM_CODE'].apply(lambda x: format(float(x), '.0f') if 'E+' in str(x) else x)
sales_week

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,WEEK,YEAR,MONTH,WEEK_NUMBER,DATE
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,01-21,2021,1,1,10/01/2021
1,34-22,7500000000000,0.487,116.519,2.916,TOTAL AUTOS AREA 5,02-21,2021,1,2,17/01/2021
2,34-22,7700000000000,1.391,68.453,5.171,TOTAL AUTOS AREA 5,03-21,2021,1,3,24/01/2021
3,34-22,7500000000000,0.022,1.481,1.833,TOTAL AUTOS AREA 5,04-21,2021,1,4,31/01/2021
4,34-22,7500000000000,2.037,182.839,5.375,TOTAL AUTOS AREA 5,05-21,2021,2,5,07/02/2021
...,...,...,...,...,...,...,...,...,...,...,...
151,44-22,7500000000000,0.772,32.419,2.756,TOTAL AUTOS AREA 2,48-23,2023,12,48,04/12/2023
152,44-22,7500000000000,0.513,14.107,3.800,TOTAL AUTOS AREA 2,49-23,2023,12,49,11/12/2023
153,44-22,7500000000000,12.849,227.073,26.658,TOTAL AUTOS AREA 2,50-23,2023,12,50,18/12/2023
154,44-22,7500000000000,19.887,345.292,31.973,TOTAL AUTOS AREA 2,51-23,2023,12,51,25/12/2023
155,44-22,7500000000000,7.119,194.320,15.510,TOTAL AUTOS AREA 2,52-23,2023,1,52,01/01/2024

## Prod_Sale
### (DataFrame unido)

In [46]:
#Limpieza del DataFrame eliminando duplicados y transformacion de tipos de datos
prod_sale = prod_sale.dropna()
prod_sale = prod_sale.drop_duplicates()
prod_sale ['CATEGORY'] = prod_sale['CATEGORY'].astype(int)
prod_sale['ITEM_CODE'] = prod_sale['ITEM_CODE'].astype(str)

prod_sale

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,INDS. ALEN,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,INDS. ALEN,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.50E+12,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,INDS. ALEN,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.70E+12,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,INDS. ALEN,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.50E+12,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,INDS. ALEN,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.50E+12,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA,jun-22,7.50E+12,0.194,8.375,4.311,TOTAL AUTOS AREA 2
501,INDS. ALEN,CLORALEX,7.50E+12,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,jun-22,7.50E+12,0.246,12.975,2.216,TOTAL AUTOS AREA 2
502,INDS. ALEN,CLORALEX,-,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,jun-22,7501681100650BP1,0.435,5.788,9.255,TOTAL AUTOS AREA 2
503,CLOROX,CLOROX,-,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS,jun-22,7.50E+12,1.097,16.307,14.064,TOTAL AUTOS AREA 2
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,jun-22,7.50E+12,0.176,10.977,3.385,TOTAL AUTOS AREA 2

In [47]:
#Estandarizacion de la columna WEEK
meses = {
    'ene': '01', 'feb': '02', 'mar': '03', 'abr': '04',
    'may': '05', 'jun': '06', 'jul': '07', 'ago': '08',
    'sep': '09', 'oct': '10', 'nov': '11', 'dic': '12'}
def convertir_mes(valor):
    if isinstance(valor, str) and '-' in valor:
        parte1, parte2 = valor.split('-')
        parte1 = parte1.lower().strip()
        
        if parte1 in meses:
            return f"{meses[parte1]}-{parte2}"
    
    return valor

prod_sale['WEEK'] = prod_sale['WEEK'].apply(convertir_mes)
prod_sale

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,INDS. ALEN,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,INDS. ALEN,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.50E+12,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,INDS. ALEN,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.70E+12,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,INDS. ALEN,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.50E+12,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,INDS. ALEN,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7.50E+12,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA,06-22,7.50E+12,0.194,8.375,4.311,TOTAL AUTOS AREA 2
501,INDS. ALEN,CLORALEX,7.50E+12,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,06-22,7.50E+12,0.246,12.975,2.216,TOTAL AUTOS AREA 2
502,INDS. ALEN,CLORALEX,-,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,06-22,7501681100650BP1,0.435,5.788,9.255,TOTAL AUTOS AREA 2
503,CLOROX,CLOROX,-,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS,06-22,7.50E+12,1.097,16.307,14.064,TOTAL AUTOS AREA 2
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,06-22,7.50E+12,0.176,10.977,3.385,TOTAL AUTOS AREA 2

In [48]:
#Estandarizacion de la columna ITEM y ITEM_CODE
prod_sale['ITEM_CODE'] = prod_sale['ITEM_CODE'].astype(str)
prod_sale['ITEM_CODE'] = prod_sale['ITEM_CODE'].apply(lambda x: format(float(x), '.0f') if 'E+' in str(x) else x)
prod_sale['ITEM'] = prod_sale['ITEM'].astype(str)
prod_sale['ITEM'] = prod_sale['ITEM'].apply(lambda x: format(float(x), '.0f') if 'E+' in str(x) else x)
prod_sale

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,INDS. ALEN,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,INDS. ALEN,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7500000000000,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,INDS. ALEN,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7700000000000,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,INDS. ALEN,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7500000000000,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,INDS. ALEN,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7500000000000,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA,06-22,7500000000000,0.194,8.375,4.311,TOTAL AUTOS AREA 2
501,INDS. ALEN,CLORALEX,7500000000000,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,06-22,7500000000000,0.246,12.975,2.216,TOTAL AUTOS AREA 2
502,INDS. ALEN,CLORALEX,-,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,06-22,7501681100650BP1,0.435,5.788,9.255,TOTAL AUTOS AREA 2
503,CLOROX,CLOROX,-,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS,06-22,7500000000000,1.097,16.307,14.064,TOTAL AUTOS AREA 2
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,06-22,7500000000000,0.176,10.977,3.385,TOTAL AUTOS AREA 2

In [52]:
# Union y limpieza de DataFrames unidos 
prod_sale_week = pd.concat([prod_sale,sales_week], axis = 1)
prod_sale_week = prod_sale_week.fillna(0)
prod_sale_week = prod_sale_week.loc[:, ~prod_sale_week.columns.duplicated() ]
prod_sale_week ['YEAR'] = prod_sale_week ['YEAR'].astype(int)
prod_sale_week ['MONTH'] = prod_sale_week ['MONTH'].astype(int)
prod_sale_week ['WEEK_NUMBER'] = prod_sale_week ['WEEK_NUMBER'].astype(int)
prod_sale_week

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,YEAR,MONTH,WEEK_NUMBER,DATE
0,INDS. ALEN,CLORALEX,75000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,2021,1,1,10/01/2021
1,INDS. ALEN,CLORALEX,75000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7500000000000,0.487,116.519,2.916,TOTAL AUTOS AREA 5,2021,1,2,17/01/2021
2,INDS. ALEN,CLORALEX,75000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7700000000000,1.391,68.453,5.171,TOTAL AUTOS AREA 5,2021,1,3,24/01/2021
3,INDS. ALEN,CLORALEX,75000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7500000000000,0.022,1.481,1.833,TOTAL AUTOS AREA 5,2021,1,4,31/01/2021
4,INDS. ALEN,CLORALEX,75000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,34-22,7500000000000,2.037,182.839,5.375,TOTAL AUTOS AREA 5,2021,2,5,07/02/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA,06-22,7500000000000,0.194,8.375,4.311,TOTAL AUTOS AREA 2,0,0,0,0
501,INDS. ALEN,CLORALEX,7500000000000,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,06-22,7500000000000,0.246,12.975,2.216,TOTAL AUTOS AREA 2,0,0,0,0
502,INDS. ALEN,CLORALEX,-,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,06-22,7501681100650BP1,0.435,5.788,9.255,TOTAL AUTOS AREA 2,0,0,0,0
503,CLOROX,CLOROX,-,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS,06-22,7500000000000,1.097,16.307,14.064,TOTAL AUTOS AREA 2,0,0,0,0
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,06-22,7500000000000,0.176,10.977,3.385,TOTAL AUTOS AREA 2,0,0,0,0

In [59]:
final_prod = prod_sale_week.groupby(
    ['ITEM', 'BRAND','WEEK','ATTR1', 'REGION']).agg({'TOTAL_UNIT_SALES': ['sum', 'median', 'std'],'TOTAL_VALUE_SALES': 'sum',
                                                                   'TOTAL_UNIT_AVG_WEEKLY_SALES': 'mean'}).reset_index()

final_prod = final_prod.fillna(0)
final_prod

                 ITEM        BRAND   WEEK        ATTR1  \

0                   -     CLORALEX  06-22        CLORO
1                   -       CLOROX  06-22        CLORO
2    0757037514016BP1    OXI CLEAN  05-22  SAFE BLEACH
3        123000000000     CLORALEX  34-22        CLORO
4         19200958714        LYSOL  34-22  SANITIZANTE
..                ...          ...    ...          ...
164     7890000000000       VANISH  06-22  SAFE BLEACH
165       79893431208  WHITE MAGIC  34-22  NO DEFINIDO
166     8410000000000       IBERIA  06-22        CLORO
167     8410000000000       IBERIA  06-22  NO DEFINIDO
168     8410000000000       IBERIA  06-22  SAFE BLEACH

                          REGION TOTAL_UNIT_SALES                   \
                                              sum median       std
0             TOTAL AUTOS AREA 2            0.435  0.435  0.000000
1             TOTAL AUTOS AREA 2            1.097  1.097  0.000000
2    TOTAL AUTOS SCANNING MEXICO            0.460  0.460  0.000000
3             TOTAL AUTOS AREA 6            0.072  0.072  0.000000
4             TOTAL AUTOS AREA 5            2.188  2.188  0.000000
..                           ...              ...    ...       ...
164           TOTAL AUTOS AREA 2            0.504  0.252  0.239002
165           TOTAL AUTOS AREA 6            0.001  0.001  0.000000
166           TOTAL AUTOS AREA 2            0.679  0.679  0.000000
167           TOTAL AUTOS AREA 2            0.192  0.192  0.000000
168           TOTAL AUTOS AREA 2           35.389  8.574  7.587335

    TOTAL_VALUE_SALES TOTAL_UNIT_AVG_WEEKLY_SALES
                  sum                        mean
0               5.788                    9.255000
1              16.307                   14.064000
2              10.209                    3.194000
3              18.880                    1.309000
4              23.792                   17.934000
..                ...                         ...
164            11.739                    3.355500
165             0.042                    1.000000
166            27.927                    2.219000
167             4.728                    2.313000
168           611.070                   20.641667

[169 rows x 10 columns]

# 5. Guardar el archivo

In [60]:
#Guardar el DataFrame Final
final_prod.to_csv("FINAL_PROD.csv")